# docs: https://docs.redislabs.com/latest/index.html
- name: Create Redis insight Dir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/redisinsight
    - /var/log/redisinsight

- name: Download Redis insight
  get_url:
    url: "{{ redis_redisinsight_url }}"
    dest: /usr/local/redisinsight/redisinsight
    mode: '0750'

- name: Config Service
  copy:
    src: redisinsight.service 
    dest: /lib/systemd/system/redisinsight.service

- name: Make dir sysconfig
  shell: if [ ! $( ls | grep sysconfig) ]; then mkdir sysconfig; fi
  args:
    chdir: /etc
    
- name: Config redisinsight
  template:
    src: redisinsight-config.jinja2
    dest: /etc/sysconfig/redisinsight-config

- name: Start redisinsight
  service:
    name: redisinsight
    state: started
    enabled: yes

- name: Set soft link for RedisInsight
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /usr/local/redisinsight,dest: /data/redisinsight}
    - {src: /var/log/redisinsight,dest: /data/logs/redisinsight}
    - {src: /etc/sysconfig/redisinsight-config,dest: /data/config/redisinsight.config}
    - {src: /etc/sysconfig/redisinsight-config,dest: /data/redisinsight/redisinsight.config}
    - {src: /usr/local/redisinsight,dest: /data/redis/redisinsight}

- name: Check RedisInsight version
  shell: >
    sudo echo "RdisInsight version:" $(curl https://docs.redislabs.com/latest/ri/release-notes/ | grep "RedisInsight v" |sed -n 1p |tr -d "</p>") |tee -a /data/logs/install_version.txt